nav:
  - Parcerias: index.md
  - Acordos de Cooperação Técnica: act
  - Modelo OSCIP/OS: descentralizacao
  - Fundações de Apoio: fundacoes
  - Marco Regulatório do Fomento à Cultura: marco-do-fomento 
  - MROSC: mrosc 